# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cfg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cfg.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tcfg.proto\"\x8a\x06\n\x12\x43ontextFreeGrammar\x12,\n\x05nodes\x18\x01 \x03(\x0b\x32\x1d.ContextFreeGrammar.TokenNode\x12<\n\x10production_rules\x18\x02 \x03(\x0b\x32\".ContextFreeGrammar.ProductionRule\x12\x32\n\x0bvalue_rules\x18\x03 \x03(\x0b\x32\x1d.ContextFreeGrammar.ValueRule\x12\x35\n\x0e\x64isabled_nodes\x18\x04 \x03(\x0b\x32\x1d.ContextFreeGrammar.TokenNode\x12\x38\n\x11whitelisted_nodes\x18\x05 \x03(\x0b\x32\x1d.ContextFreeGrammar.TokenNode\x1a\xed\x02\n\tTokenNode\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x14\n\x0c\x63\x61nonical_id\x18\x02 \x01(\x05\x12\x17\n\x0fpossible_values\x18\x03 \x03(\t\x12\x14\n\x0c\x63hosen_value\x18\x04 \x01(\t\x12\x18\n\x10is_terminal_node\x18\x05 \x01(\x08\x12\x18\n\ncan_repeat\x18\x06 \x01(\x08:\x04true\x12\x1e\n\x0fsolr_query_node\x18\x07 \x01(\x08:\x05\x66\x61lse\x12\x1a\n\x0b\x65ntity_node\x18\x08 \x01(\x08:\x05\x66\x61lse\x12\x1a\n\x0bmetric_node\x18\t \x01(\x08:\x05\x66\x61lse\x12\x1a\n\x0b\x66ilter_node\x18\n \x01(\x08:\x05\x66\x61lse\x12\x1c\n\rgroup_by_node\x18\x0b \x01(\x08:\x05\x66\x61lse\x12!\n\x12single_entity_node\x18\x0c \x01(\x08:\x05\x66\x61lse\x12$\n\x15is_visit_segment_node\x18\r \x01(\x08:\x05\x66\x61lse\x1a\x37\n\x0eProductionRule\x12\r\n\x05node1\x18\x01 \x02(\x05\x12\x16\n\x0e\x61\x64jacent_nodes\x18\x02 \x03(\x05\x1a:\n\tValueRule\x12\r\n\x05node1\x18\x01 \x02(\x05\x12\r\n\x05node2\x18\x02 \x02(\x05\x12\x0f\n\x07op_node\x18\x03 \x02(\x05'
)




_CONTEXTFREEGRAMMAR_TOKENNODE = _descriptor.Descriptor(
  name='TokenNode',
  full_name='ContextFreeGrammar.TokenNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ContextFreeGrammar.TokenNode.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='canonical_id', full_name='ContextFreeGrammar.TokenNode.canonical_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='possible_values', full_name='ContextFreeGrammar.TokenNode.possible_values', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chosen_value', full_name='ContextFreeGrammar.TokenNode.chosen_value', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_terminal_node', full_name='ContextFreeGrammar.TokenNode.is_terminal_node', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='can_repeat', full_name='ContextFreeGrammar.TokenNode.can_repeat', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='solr_query_node', full_name='ContextFreeGrammar.TokenNode.solr_query_node', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entity_node', full_name='ContextFreeGrammar.TokenNode.entity_node', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metric_node', full_name='ContextFreeGrammar.TokenNode.metric_node', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filter_node', full_name='ContextFreeGrammar.TokenNode.filter_node', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='group_by_node', full_name='ContextFreeGrammar.TokenNode.group_by_node', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='single_entity_node', full_name='ContextFreeGrammar.TokenNode.single_entity_node', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_visit_segment_node', full_name='ContextFreeGrammar.TokenNode.is_visit_segment_node', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=675,
)

_CONTEXTFREEGRAMMAR_PRODUCTIONRULE = _descriptor.Descriptor(
  name='ProductionRule',
  full_name='ContextFreeGrammar.ProductionRule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='node1', full_name='ContextFreeGrammar.ProductionRule.node1', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='adjacent_nodes', full_name='ContextFreeGrammar.ProductionRule.adjacent_nodes', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=677,
  serialized_end=732,
)

_CONTEXTFREEGRAMMAR_VALUERULE = _descriptor.Descriptor(
  name='ValueRule',
  full_name='ContextFreeGrammar.ValueRule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='node1', full_name='ContextFreeGrammar.ValueRule.node1', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node2', full_name='ContextFreeGrammar.ValueRule.node2', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='op_node', full_name='ContextFreeGrammar.ValueRule.op_node', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=734,
  serialized_end=792,
)

_CONTEXTFREEGRAMMAR = _descriptor.Descriptor(
  name='ContextFreeGrammar',
  full_name='ContextFreeGrammar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes', full_name='ContextFreeGrammar.nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='production_rules', full_name='ContextFreeGrammar.production_rules', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value_rules', full_name='ContextFreeGrammar.value_rules', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='disabled_nodes', full_name='ContextFreeGrammar.disabled_nodes', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='whitelisted_nodes', full_name='ContextFreeGrammar.whitelisted_nodes', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CONTEXTFREEGRAMMAR_TOKENNODE, _CONTEXTFREEGRAMMAR_PRODUCTIONRULE, _CONTEXTFREEGRAMMAR_VALUERULE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=792,
)

_CONTEXTFREEGRAMMAR_TOKENNODE.containing_type = _CONTEXTFREEGRAMMAR
_CONTEXTFREEGRAMMAR_PRODUCTIONRULE.containing_type = _CONTEXTFREEGRAMMAR
_CONTEXTFREEGRAMMAR_VALUERULE.containing_type = _CONTEXTFREEGRAMMAR
_CONTEXTFREEGRAMMAR.fields_by_name['nodes'].message_type = _CONTEXTFREEGRAMMAR_TOKENNODE
_CONTEXTFREEGRAMMAR.fields_by_name['production_rules'].message_type = _CONTEXTFREEGRAMMAR_PRODUCTIONRULE
_CONTEXTFREEGRAMMAR.fields_by_name['value_rules'].message_type = _CONTEXTFREEGRAMMAR_VALUERULE
_CONTEXTFREEGRAMMAR.fields_by_name['disabled_nodes'].message_type = _CONTEXTFREEGRAMMAR_TOKENNODE
_CONTEXTFREEGRAMMAR.fields_by_name['whitelisted_nodes'].message_type = _CONTEXTFREEGRAMMAR_TOKENNODE
DESCRIPTOR.message_types_by_name['ContextFreeGrammar'] = _CONTEXTFREEGRAMMAR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ContextFreeGrammar = _reflection.GeneratedProtocolMessageType('ContextFreeGrammar', (_message.Message,), {

  'TokenNode' : _reflection.GeneratedProtocolMessageType('TokenNode', (_message.Message,), {
    'DESCRIPTOR' : _CONTEXTFREEGRAMMAR_TOKENNODE,
    '__module__' : 'cfg_pb2'
    # @@protoc_insertion_point(class_scope:ContextFreeGrammar.TokenNode)
    })
  ,

  'ProductionRule' : _reflection.GeneratedProtocolMessageType('ProductionRule', (_message.Message,), {
    'DESCRIPTOR' : _CONTEXTFREEGRAMMAR_PRODUCTIONRULE,
    '__module__' : 'cfg_pb2'
    # @@protoc_insertion_point(class_scope:ContextFreeGrammar.ProductionRule)
    })
  ,

  'ValueRule' : _reflection.GeneratedProtocolMessageType('ValueRule', (_message.Message,), {
    'DESCRIPTOR' : _CONTEXTFREEGRAMMAR_VALUERULE,
    '__module__' : 'cfg_pb2'
    # @@protoc_insertion_point(class_scope:ContextFreeGrammar.ValueRule)
    })
  ,
  'DESCRIPTOR' : _CONTEXTFREEGRAMMAR,
  '__module__' : 'cfg_pb2'
  # @@protoc_insertion_point(class_scope:ContextFreeGrammar)
  })
_sym_db.RegisterMessage(ContextFreeGrammar)
_sym_db.RegisterMessage(ContextFreeGrammar.TokenNode)
_sym_db.RegisterMessage(ContextFreeGrammar.ProductionRule)
_sym_db.RegisterMessage(ContextFreeGrammar.ValueRule)


# @@protoc_insertion_point(module_scope)
